### ISSUE TITLE
a tweak to make federated macrosynteny easier?

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/lis_context_viewer#10]
I'd like to propose the following change
diff --git a/client/app/selectors/macro-tracks.selector.ts b/client/app/selectors/macro-tracks.selector.ts
index f4bff02..663c9bc 100644
--- a/client/app/selectors/macro-tracks.selector.ts
+++ b/client/app/selectors/macro-tracks.selector.ts
@@ -6,7 +6,7 @@ export const macroTracksSelector = (filter, order) => {
       if (macroTracks !== undefined && filteredMicroTracks.groups.length > 0) {
         let query = filteredMicroTracks.groups[0];
         let chrs = filteredMicroTracks.groups.reduce((l, g, i) => {
-          if (i > 0 && g.source == query.source) l.push(g.chromosome_name);
+          if (i > 0) l.push(g.chromosome_name);
           return l;
         }, []);
         let macro = Object.assign({}, macroTracks);

not requiring "same sourceness" appears to be just what I needed to allow macrosynteny blocks defined on one source with respect to a chromosome whose actual gene content is found in another source to play nicely with respect to the macro-micro coordinated views. See any downsides to this (assuming we can trust "names" to be identifying cross-source)?

**Comment by adf-ncgr** [comment]
oops forgot to @alancleary that one (though I doubt it is actually needed to get your attention)

**Comment by alancleary** [comment]
That seems fine to me; the code was written under the assumption that no macro-synteny track could have a chromosome that wasn't provided by the source of the micro-synteny query track!

**Comment by adf-ncgr** [comment]
resolved by 464df28
