### ISSUE TITLE
repeat algorithm sometimes "eats" copy number variation?

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/lis_context_viewer#104]
the only example of this I have at the moment is with respect to the new gene families defined on lis-dev, but I suspect it occurs elsewhere without my having noticed it.  

Compare : repeat algorithm 
/lis_context_viewer/#/search/lis/glyma.Glyma.08G224600?neighbors=15&sources=lis&matched=4&intermediate=5&algorithm=repeat&match=10&mismatch=-1&gap=-1&score=30&threshold=40&regexp=medtr&order=chromosome&alpha=0.85&kappa=10&minsup=2&minsize=5
![image](https://user-images.githubusercontent.com/2009605/34144834-9c4b9d48-e450-11e7-8811-2b9234cd3b9f.png)
to : smith waterman
/lis_context_viewer/#/search/lis/glyma.Glyma.08G224600?neighbors=15&sources=lis&matched=4&intermediate=5&algorithm=smith-waterman&match=10&mismatch=-1&gap=-1&score=30&threshold=40&regexp=medtr&order=chromosome&alpha=0.85&kappa=10&minsup=2&minsize=5
![image](https://user-images.githubusercontent.com/2009605/34144859-baf1afbc-e450-11e7-8763-c2f02a88f562.png)

with respect to the genes in the family that is the "focus". one of the medtr copies (Medtr4g005390) seems to disappear altogether from the alignment (can't even find it in the list of genes given in the track slider, so it must not just be a question of "optics"...)

**Comment by alancleary** [comment]
Fixed in commit d849675fd78f2d74a0a20e8c12eefb5826b2f373. Also discovered and fixed a bug that caused the ordering of inserted genes to be reversed!
