### ISSUE TITLE
Support multiple API versions

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/lis_context_viewer#111]
The on-demand macro-synteny service was not defined in version 1 of the GCV services API and will, perhaps, replace the static macro-synteny service in the next version of the API. It would be ideal if the client app could support both versions of the API so it can load data from providers that have implemented/deployed different API versions. Perhaps the app should assume providers implement the most recent version of the API and fallback to an older version that implements the same or similar functionality if necessary. Alternatively, we could have providers tell the app what version they implement, either via a service or encoding the API version in urls or response headers.

**Comment by alancleary** [comment]
Might be worth looking into GraphQL.

**Comment by adf-ncgr** [comment]
Hmm, I think @joelb was urging exploration of GraphQL some time ago, but it's not entirely clear to me how it applies here; I see the bit about evolving APIs without versioning them, which might be the connection. Anyway, it does look interesting and I'd be happy to find a compelling use for it, but we should probably spend some time making sure we're thinking about it from a roughly similar perspective before diving in too deep...

**Comment by alancleary** [comment]
Yes, I think some careful thought is definitely required on this one. Was just reminded of this recently and wanted to put it on the table before I forgot!

**Comment by alancleary** [comment]
Spent some time looking into GraphQL and I'm not sold. They do away with API versioning (which is what really piqued my interested in the first place) by taking an "add-only" approach, that is, you only add new things to the API while old things remain unchanged. You can do this with a REST API too, so what else does GraphQL bring to the table? It's real power lies in the query language itself, which enables clients to make very specific queries, e.g., I want the name and description of every product this user bought before January 1, 1900. Though this could work with the GCV - e.g. get me the query track for this gene and all related contexts and macro synteny blocks - it doesn't work in the federated scenario. In other words, we **need** our data loading to be multiple, sequential requests because certain requests depend on the result of previous requests to other sources. So unless we want to abstract the federation behind a single API that the client interacts with (which I certainly don't), then GraphQL doesn't seem appropriate.
