### ISSUE TITLE
Add support for structures other than chromosomes in the macro-synteny viewer

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/lis_context_viewer#118]
Currently the on-demand macro-synteny service only computes blocks for chromosomes. Some users may want to compute blocks for other structures, such as scaffolds and super-contigs. Make this a tunable option in the macro-synteny viewer's context menu.

**Comment by adf-ncgr** [comment]
let's leave it to the service provider config for the time being (at least until any real users ask for it)
