### ISSUE TITLE
gene families represented in multiple copies per track probably should not count independently towards region support

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/lis_context_viewer#12]
as with the approach we've taken for finding candidate alignment tracks in the search view, I think we ought to only count distinct gene family instances as contributing to a track's support for an FR. for example here is a group whose two members have very little in common and I'm guessing that the way each individually meets the FR criterion is by having multiple instances of genes that were added to the FR (note that these repeated families don't themselves appear to be shared between the two tracks in this case):

![image](https://user-images.githubusercontent.com/2009605/29319535-972a2cb6-8191-11e7-928a-9d1b965218d0.png)

**Comment by alancleary** [comment]
Each gene family can only appear once in the set of families that define a cluster. Similarly, a family can only be counted once when computing a supporting track's identity. So what we're seeing here is an unfortunate combination of FR parameters, most likely identity and min size.

Off hand, a few ways we could try and combat this are 1) prevent the FR algorithm from using genes families that only appear once in the set of non-grouped tracks and/or only appear in one track and 2) take the number of tracks a family occurs in when deciding what FRs to merge. (1) is probably easier to implemented but is more likely to negatively impact some clusterings than (2).

**Comment by adf-ncgr** [comment]
I would be hard pressed to reproduce that example, but given our conversation of hours ago regarding the nature of "identity" and your comment above it sounds like the issue as stated is close-able since it is already the case that they don't count independently towards region support. Your ideas 1) and 2) may be good, but I think the implementation has changed enough since this issue was originally filed that it's probably good to wait and see if there are still perceived problems that call for one or the other of them. But I'll have my problem-perception glasses on... I'll defer to you as to whether to close or leave this somewhere as an aide-memoire.

**Comment by alancleary** [comment]
We can address these other issues when the time comes. Closing...
