### ISSUE TITLE
when basic view tracks are flipped for inclusion in MSA, individual gene strandedness should be flipped

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/lis_context_viewer#13]
not completely sure, but I think this is probably why one of these tracks is not quite like the others

![image](https://user-images.githubusercontent.com/2009605/29745388-79dab052-8a76-11e7-945f-76b5b1b48d82.png)

**Comment by alancleary** [comment]
Fixed in commit f38e3711ea25207d49695ca44b94a8c94451a920
