### ISSUE TITLE
circos view: should any chromosome ever legitimately appear multiple times there?

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/lis_context_viewer#134]
When I look at:
http://fisher.ncgr.org:50005/lis_context_viewer/#/multi/phavu.Phvul.002G085200,glyma.Glyma.01G047700,glyma.Glyma.02G107500,phavu.Phvul.002G170900,vigun.Vigun02g060600,vigun.Vigun03g207900?neighbors=10&matched=4&intermediate=5&algorithm=repeat&match=10&mismatch=-1&gap=-1&score=30&threshold=25&regexp=&order=distance&sources=lis&bintermediate=10&bmask=10&bmatched=20&alpha=0.85&kappa=10&minsize=5&minsup=2

I think I see 2 instances of phavu.Chr02 in the circos, probably corresonding to the fact that there are two separate phavu.Chr02 microtracks. However, only one of the circos segments is collecting macro-blocks. I suspect that there is no good reason to represent a chromosome more than once in the circos view, unless we want to make separate circles for different clusters of tracks, in which case I suspect there is no good reason to represent a chromosome more than once per circle.

**Comment by alancleary** [comment]
Fixed in commit 0312f2cb177fa4754b6ff0c3d02bd5af50249b03.
