### ISSUE TITLE
Extend HMM topology to handle structural variations of itnerest

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/lis_context_viewer#14]
In the search view, the Repeat algorithm is used to capture structural variations, such as inversions. It would be nice to capture such structural variations in the basic MSAs as well. This will require modifying the HMM, likely its topology.

**Comment by adf-ncgr** [comment]
thanks for adding this. One thought that just came to mind which I will note while it is somewhat fresh if not very coherent: we may want to think more about the relationship between what we're doing here on the scale of restricted neighborhoods of genes and what happens as those neighborhoods grow to scales that are more truly pangenomic, in which it becomes more likely that not only inversions but also translocations could be significant. So for example how will we want to handle the case in which one track has only partial alignment to the consensus representation but another track from that same genome (e.g. a different chromosome or a widely separated segment of the same chromosome) picks up the remainder of the syntenic content. This will probably be more of an immediate issue if we switch some version of the search view over to using this type of model-based alignment strategy. We did at one point discuss the variant HMM topologies for local alignment, which will likely come into play here, but I'm also vaguely thinking about the larger genome graph structure and how FRs and sequences of FRs might fit into higher-order strategies for "probabilistic alignment" (something I think we may have discussed briefly near the beginning of the summer?).

**Comment by alancleary** [comment]
Commits 1c79a32c8d41810061c07395de440be1a1f14019 and 7b1c0ad29d34c6ea7f191eec786b907c13840d00 introduced code that handles the identification and explicit drawing of inversions. Since the other types of structural variation we may be interested in drawing are relatively uncommon, this issue will be closed until we decide the need justifies an issue.
