### ISSUE TITLE
circos view- are we getting doubling of macroblocks in the viewer?

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/lis_context_viewer#141]
not exactly sure, but when I look at the arcs displayed on the circumference of the multi-macro view on lis-stage (having just merged your last round of commits) I think I see evidence that every pairwise syntenic block has two blocks (at least?) on either side of the chord relating them. Look at /lis_context_viewer/#/multi/phavu.Phvul.002G085200,glyma.Glyma.01G047700,glyma.Glyma.02G107500,phavu.Phvul.002G170900,vigun.Vigun02g060600,vigun.Vigun03g207900?neighbors=10&matched=4&intermediate=5&algorithm=repeat&match=10&mismatch=-1&gap=-1&score=30&threshold=25&regexp=&order=distance&sources=lis&bintermediate=10&bmask=10&bmatched=20&alpha=0.85&kappa=10&minsize=5&minsup=2
for example.
I'm not sure they are all doubled, but if you filter down the above to show only phavu.Chr02 and its self-synteny you may see what appear to be 4 blocks on either side of the one chord. 

(also, after doing this I think I noticed that the "you are here" red marks in the circumference did not see to correspond to where I thought I was, though I suppose this could be a mistaken interpretation if the microblocks did not actually correspond to any macroblocks at the given parameterizations)

**Comment by alancleary** [comment]
@adf-ncgr Good catch. It seems blocks are being replicated for each time a chromosome appears in the micro-synteny view. So in your example any block relative to phavu.Chr02 appears twice.

**Comment by alancleary** [comment]
Fixed in commit 755307eb9fa82d91244d3c4240fefc2d94271842.

Regarding the "you are here" markers in the circumference of the multi-macro viewer: they seem to agree with their counterparts in the search view's macro viewer.
