### ISSUE TITLE
track id collision manifested in dotplot

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/lis_context_viewer#154]
It seems that in micro-tracks.service.ts the _parseTrack method assigns a default value of 0 to the
i parameter that is ultimately used to construct an id for the track as
`track.id = source + i;`
it looks like the query track is probably getting a track id that relies on the use of the default,
and so collides with the track whose position in the returned set of tracks as microsyntenic
to the query (when they are from the same source). A valid solution (at least, one that solves the problem I've been debugging) is to change the function as:
`  private _parseTrack(source: string, track: Group, i:number = -1): void {`
Not sure this is elegant or won't cause other problems, so deferring to @alancleary judgment.

**Comment by alancleary** [comment]
@adf-ncgr As far as I can tell your fix has no unintended side-effects; done in commit ce45b7b37e1a8cc6e4bfca476e0e3dfaa2d2d0cb. Closing.
