### ISSUE TITLE
consider switching some param values to represent percentages of num neighbors

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/lis_context_viewer#161]
when expanding num neighbors, it is easy for those not well-versed in the art of param-tweaking to get lots and lots of blocks (because they haven't adjusted min matched families to compensate); a similar adjustment could be made for the alignment threshold score, although that would be have to be done in terms of a theoretical max score based on the scoring params in play (I guess?). This came up because of some actual user's behavior when trying to use GCV to deal with largish regions identified by QTL mapping...

**Comment by alancleary** [comment]
This seems reasonable. The alignment adjustment is probably involved enough that it should have its own issue; creating now.

**Comment by alancleary** [comment]
In an recent email exchange with @adf-ncgr, he suggested a very reasonable solution:

> take the value given for a parameter as "absolute" if >1 and as a percentage if <= 1

Make it so!

**Comment by alancleary** [comment]
Commit 238d4998decafe511dd5d0f47ec25cd5e99e1a9e added support for the previously described scheme to the server. Commit 183755aba79bb50c9de89c427d713906d0df0e25 added support to the client.
