### ISSUE TITLE
sort order of tracks should be preserved in URL

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/lis_context_viewer#164]
seems like the param isn't getting set in latest code, so everytime a new query is made one has to resort if not using the default.

**Comment by adf-ncgr** [comment]
I guess this may be a more general case of URL params not being used to set initialState, for example in this case I think we are getting:
export const initialState: State = {orderAlgorithm: ORDER_ALGORITHMS[0]};

when a URL with order=distance is dereferenced. and similarly with the filter:
export const initialState: State = {
  regexpAlgorithm: regexpAlgorithmFactory(""),
};

**Comment by alancleary** [comment]
The regular expression used to filter tracks appears to not be saved in the url query params either.

**Comment by alancleary** [comment]
Fixed in commits dca3ff289397da264b47aa6142457efdfe0193c9 and ad4ae98ef3c721774b1a07a5788722caa4f36ead.
