### ISSUE TITLE
Base url not behaving as expected

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/lis_context_viewer#166]
When compiling GCV to be deployed on a sub-url, such as /lis_context_viewer/, the base url must be set so that the app knows where to load its resources from. This can be done by setting the href attribute of the base tag in index.html or by passing the --base-href flag to ng build. Unfortunately, the relative URLs used throughout the application assume that GCV is being served from the root of the domain and therefore are broken when the base url is set to a value other than root. Furthermore, other unexpected behaviors have been observed, such as the GCV loading correctly on a sub-url but then throwing a 404 when reloaded.

**Comment by adf-ncgr** [comment]
thanks for setting up the issue for this. One thing that might be worth thinking about. In "olden days" (ie before the changes on this branch) the search URL would have been:
https://legumeinfo.org/lis_context_viewer/#/search/lis/phavu.Phvul.002G085200 etc
where according to my limited understanding the # would be somewhat critical in mediating the handoff between apache loading the index document and then the client getting all the URL stuff following the # to deal with. The new style URLs don't seem to rely on # which may contribute to the problem?

**Comment by alancleary** [comment]
The # delimiter was removed when introducing bootstrap tours into the config branch. This is because changes to the URL that occurred after the # were not recognized by bootstrap tours thus preventing the tour from progressing.

Regarding the 404s mentioned in the OP, perhaps Apache needs to be configured so that it doesn't try to resolve URLs beyond the GCV's base url, but rather, directs all requests prefixed with the base url to GCV.

**Comment by adf-ncgr** [comment]
that's a thought; I will try to figure out how to achieve it, but if you know offhand, hints accepted.

**Comment by alancleary** [comment]
I don't know offhand, but this SO answer looks promising: https://stackoverflow.com/a/36590784

**Comment by adf-ncgr** [comment]
yes, that seems to be getting me closer (actually trying the one from which yours says it was adapted:
https://stackoverflow.com/questions/35198319/angular-2-routing-and-direct-access-to-a-specific-route-how-to-configure-apach)

bonus: I just learned that hashtag URL solutions will get you downvoted:
"because no decent developer should ever use a hashtag without no partical reason in an angular2 app..."
such a fickle bunch!

**Comment by adf-ncgr** [comment]
I think that the SO solution has handled the 404 errors but there is still one major thing that is baffling me.
It is in the "harder to describe" category, but basically under conditions I don't understand but not infrequent,
when I go to the /lis_context_viewer/search/...
I get shunted over to /search/...

sometimes this even mysteriously happens when I go to /lis_context_viewer/instructions (ie I get shunted off to a /search/....
previously performed (but without the /lis_context_viewer/ base this time).

it doesn't seem to be any http redirection and it was actually happening prior to the implementation of the fix for the 404 error.

if you might need a live demo to make sense of it, I can arrange a screenshare or whatever works.

**Comment by alancleary** [comment]
The in-app URLs that weren't accounting for the base href prefix have been updated in commit 0a50a7ff0e38911edf1379e5896db6dae407c53e. Unfortunately (?) the configurable URLs, specifically those listed in the config.json file and the default tour, are not automatically updated to include this prefix. This is because it was non-trivial to make this change, but it also falls in line with the purpose of the configuration having such things being configurable.

Regarding the "harder to describe" behavior; I've witnessed this behavior as well. It seems to happen when navigating from one GCV url to another and base href is not /. Will look into it.

**Comment by adf-ncgr** [comment]
agreed that configurability implies the configurator can handle the base-urls in the configuration.
I am glad that you are on the case with respect to the other behavior. It is very disconcerting!

**Comment by alancleary** [comment]
Apparently neither of us is a very good configurator - the weird redirecting behavior we've been observing is the default tour being resumed and trying to redirect to its paths that aren't prefixed with the base href! So setting the "basePath" attribute of the Tour object resolves the issue.

The problem now is that every time the tour goes to the next/previous step it reloads the entire page because of the base href prefix. I'm looking into this now; will probably require a custom "redirect" function, as described in the bootstrap tour API.

**Comment by alancleary** [comment]
That's odd. Perhaps an old, in progress instance of the tour was being loaded from local storage.

I've pushed a commit (5fbf89f82aa7d65a6e4875e7c1867e5d90d36b54) that introduces a "basePath" variable in the default tour so that updating the tour for an instance of the GCV being served with a non-root base href is as simple as updating this variable.

Unfortunately there are still some issues. Namely, if the path provided for any one step doesn't include all the query parameters that GCV uses, then the page will be reloaded rather than the app updating in a single-page manner. Also, when a tour is in progress and a GCV url that doesn't correspond to the current tour step is loaded, rather than redirecting to the current step, the tour throws a redirection loop error and terminates.

**Comment by adf-ncgr** [comment]
Thanks for the update- this sounds like a step in the right direction, though I probably won't be able to give it any serious attention for a few days. In the meantime, can you remind me why you found it advisable to require the path be specified for each and every step of the tour- was it primarily for allowing back-navigation (ie use of Prev button)? My general experience with "path" has been that it tends to make the tours a little more finicky/brittle, and I think most of the LIS tours basically just suppress the Prev button to avoid some of the complications (ie I am willing to abandon the feature of bidirectional navigation if that helps resolve any of the remaining issues you're having).

**Comment by alancleary** [comment]
Yes, every step has a path for navigation purposes, also so that the tour may be resumed at an arbitrary step.

Regarding the remaining issues, it seems having the GCV redirect at every step can be prevented by defining each step's path as a regular expression. That way bootstrap tour can see that the URLs are effectively equivalent even though GCV has added some additional query parameters.

As far as resuming the tour is concerned, I'm not particularly worried about this being broken. I've actually been contemplating removing this functionality, or at least asking the user whether or not they want to resume the tour, because it's annoying to be redirected from the context you were loading to wherever the tour was left at.

**Comment by adf-ncgr** [comment]
OK, sounds like you are learning some touring tricks I was unaware of (e.g. the regex functionality of paths). If you think you have something close to working, I will just see what you come up with as the default tour and if I want to make LIS's different for whatever reason that should simply be within the scope of my configutorial privilege ;)

**Comment by alancleary** [comment]
Commit d207abf2da1085c6a23afeb1a03e8eea57f088c8 fixed a few redirection related issues: 1) tour steps now use regular expressions to match URLs that GCV has added extra query parameters to, 2) tours can now use Angular's routing mechanism to perform redirects without reloading the entire page, and 3) the tour service now reinitializes every tour after each route change so that tours can be resumed from arbitrary places and after single-page route changes.

**Comment by alancleary** [comment]
Commit 3278dda3930ecf93a074f4b45412de584679e980 updated the default tour to account for the fact that the Angnular routing mechanism already accounts for the base url whereas bootstrap tour does not.

Though there are still a few tour related issues, this should wrap up those concerning the base url.
