### ISSUE TITLE
Ask the user if they want to resume the tour

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/lis_context_viewer#168]
Currently when a user loads a page and a tour is in progress, if the page they're loading doen't correspond to the current step of the tour then they will be redirected to the correct page and the tour will resume. This is annoying if you are trying to bail from the tour currently in progress or you're trying to load a page that's completely unrelated to the tour. For this reason, if there is a tour that can be resumed, the user should be given the option to resume the tour, rather than being forced back into it.

**Comment by alancleary** [comment]
Using the magic of ZenHub, I've replicated this issue in the lis_tours repository (legumeinfo/lis_tours#1). I left this one open in case the solution here is specific to GCV.

**Comment by adf-ncgr** [comment]
You have done well to use the way of the Zenhub, grasshopper...

**Comment by alancleary** [comment]
This functionality has been introduced in commit 66544555f22e8188bd24ba9235c262110eb2b2ed. The solution is not GCV specific so it can be used to resolve legumeinfo/lis_tours#1, but it requires a custom redirect function and checking the value of a "hidden" variable in the tour object. It might be worth opening an issue on the bootstrap tour repo to request a getter method for checking this value.
