### ISSUE TITLE
make url to iconography cfgable?

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/lis_context_viewer#172]
in index.html the 
  <link rel="icon" type="image/x-icon" href="favicon.ico">
is subject to someone like me wanting to change it to:
  <link rel="icon" type="image/x-icon" href="/sites/default/files/favicon_0.ico">

of course, it's easy enough to hack in there, and perhaps the argument for making it yet another property in the config.json is weak. I'll leave the decision to you (with the proviso that it shouldn't consume too much of your valuable time...)

**Comment by alancleary** [comment]
I presume you're referring to the link tag that loads the favicon. I've actually been meaning to make this configurable via config.json but haven't gotten around to it. Thanks for adding a ticket!

**Comment by alancleary** [comment]
Done in commit b63b11ffa9048ad0260255222d99206f9125bf3d.

**Comment by alancleary** [comment]
Forgot to remove the Angular favicon from the angular cli config file. Reopening.

**Comment by alancleary** [comment]
Done in commit 9ca47deda6859b942716f47b8a7837057dc61e02.
