### ISSUE TITLE
how hard would it be to support (re-route) old hash-style URLs for previously formulated links

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/lis_context_viewer#185]
it seems like it would be worth doing if relatively simple.

**Comment by cann0010** [comment]
@adf-ncgr Can you give an example, and the context?

**Comment by adf-ncgr** [comment]
Sure, we used to have URLs that looked like this:
http://legumeinfo.org/lis_context_viewer/#/search/phavu.Phvul.002G025100
(from a bookmarked example I have)
now accessing that will redirect to:
https://legumeinfo.org/lis_context_viewer/instructions
rather than to 
http://legumeinfo.org/lis_context_viewer/search/phavu.Phvul.002G025100
which is the new official way to ask for it.

I had recently run into yet another place (the linkout service for multi-view) where I had forgotten to
make the change, hence this issue.

The # here is an example of https://en.wikipedia.org/wiki/Fragment_identifier note in particular this clause:
"The fragment identifier functions differently to the rest of the URI: its processing is exclusively client-side with no participation from the web server, though the server typically helps to determine the MIME type, and the MIME type determines the processing of fragments. When an agent (such as a Web browser) requests a web resource from a Web server, the agent sends the URI to the server, but does not send the fragment. Instead, the agent waits for the server to send the resource, and then the agent processes the resource according to the document type and fragment value."

It makes sense with a single-page app like we have, but apparently Angular has deprecated the hash-style way of doing things and Alan I think had some additional reasons for moving to the new style of hash-less URL. But we all know that Cool URIs Don't Change https://www.w3.org/Provider/Style/URI so I thought perhaps we could accommodate (if easy)

**Comment by alancleary** [comment]
Fixed in master with hotfix fe862c413bab7b43b43cef531791234850b1c907.

**Comment by adf-ncgr** [comment]
turns out this came in handy faster than I had expected- there are links to GCV from gene pages that use the hash-style and I can never remember where these links are actually configured. yet another good reason to use service brokering (URL updates can be centralized at the registry)
