### ISSUE TITLE
Singleton genes not present in message

### ISSUE THREAD

**Issue by svengato** [legumeinfo/lis_context_viewer#192]
When you mouseover the **Singletons** "gene family", the Broadcast Channel message includes the list of singleton families, but the list of singleton genes remains empty. Shouldn't there be a one-to-one correspondence?

**Comment by alancleary** [comment]
Thanks for catching this, @svengato.

**Comment by alancleary** [comment]
Fixed by the message enrichment mechanism introduced in commit bacb3e83b07e5ed769c7d6bd0c3a7d9209e958b2.
