### ISSUE TITLE
Pay down some technical debt

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/lis_context_viewer#202]
A bit a technical debt has accrued in the GCV client, mostly in or relating to the multi and search components. The point of this epic is to address some of the more significant debt before it begins to snowball.

**Comment by adf-ncgr** [comment]
It looks like you're refinancing, maybe to take advantage of the equity you've built up... ;)

**Comment by alancleary** [comment]
Well. This issue certainly snowballed. Alas, it is done.
