### ISSUE TITLE
orphans should not lack their dotted outline when used as focus gene

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/lis_context_viewer#205]
e.g. https://legumeinfo.org/lis_context_viewer/search/lis/glyma.Glyma.16G158900
looks like it ought to have a family. somewhat related but perhaps not deserving of its own separate issue, orphans get an empty set of parentheses in their popups. it might be better to make it more explicit (ie. ("orphan") or some such).

**Comment by alancleary** [comment]
Fixed in commit f10ef6b95d3dbacf93212dc8b5a0a93bfc1f69ec.
