### ISSUE TITLE
user does need control over interapp communication

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/lis_context_viewer#206]
Subsequent to my directive to have @alancleary make GCV respond to messages received regarding genomic regions by updating its position in the genome, it has come to my attention that:
a) it's a powerful feature
b) with great power, comes great responsibility

in particular, I've found that while this feature enables interesting behaviors I had not anticipated (e.g. two GCVs with different gene family sets can explore in unison), on the other hand an avid GCV user like myself (who tends to have many open at a time from various threads of work in progress) will find their unattended GCVs having mysteriously shifted to new views as if a genomic poltergeist had been afoot. 

So, I think it would probably be good to disable interapp communication by default but let the interested user enable it and probably name the broadcast channel themselves as a way of controlling with whom they are in communication at any given time.

just my 2c, and we probably ought to consider alternatives that have been implemented elsewhere (e.g. in ZBrowse) before we proceed with anything that will serve as a model for future UIs to leverage.

**Comment by alancleary** [comment]
I think giving the user control is the way to go. For now this should probably be done by letting the user toggle inter-app communication and change the channel via a simple form in the GCV UI. Whether inter-app communication is enabled by default and what the default channel is should be controlled by the config file.

In the long term, the inter-app communication code (UI, channel publish-subscribe mechanism, selecting the communication medium, etc) should be encapsulated in a JavaScript library that can be used by any web app. This should be pursued in a LegFed issue.

**Comment by alancleary** [comment]
Commit 4dacad16acc6654f2bbb7ecec6d42d485da638d2 gives the user control over inter-app communication by providing a checkbox to toggle communication and an input that allows them to specify the channel. The default states of these elements are defined in the config file. Note, if the channel is undefined in the config file then the communication component will not be included in the UI.
