### ISSUE TITLE
gene-search component error handling

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/lis_context_viewer#21]
was just looking into this a bit; seems like the discussion here:
https://angular.io/guide/router#resolve-pre-fetching-component-data

is relevant to our situation. maybe- it's entirely possible I have no idea what they are talking about!

but we seem not to have a previous issue for the error handling problem that is preventing us from joyfully merging the work you did on the gene-search branch . so here it is...

**Comment by alancleary** [comment]
A simple fix for now, done in f4e72ca9fe8f39da928d4a8e0d7aab5a77940e74
