### ISSUE TITLE
Add search page

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/lis_context_viewer#210]
In the case that the user's search has matched none or multiple items, then the user should be sent to a search page that summarizes the results. In the case of a unique hit, they should be directed to the appropriate view: multi or search. The latter should probably be renamed to something that distinguishes its purpose better from the search functionality.

**Comment by alancleary** [comment]
A search module with a search component was added in commit 2e1dc03621ec900abb850cd40543de1d3c0b0385. This component should serve as the aforementioned search page.

**Comment by alancleary** [comment]
@adf-ncgr How badly do you want the user to be redirected if their search only gets one hit? This may actually be tricky to implement since search is asynchronous, i.e. the search could span multiple sources and the results are shown to the user as they come in, rather than aggregating them all first.

**Comment by adf-ncgr** [comment]
an extra click is a small price to pay for federation. meaning, I don't care about it that much, but I guess if easy to do in the special case where a GCV is communicating with a single service provider that could be a compromise position. We will still be able to circumvent search altogether by linking in directly from gene pages, etc. So I suppose we could also support an "I'm feeling lucky" sort of input box that either made them feel lucky if they typed the name exactly right or made them feel lucky by giving them whatever the first result that came in happened to be. Any user of GCV ought to feel lucky they have such a nice tool

**Comment by alancleary** [comment]
@adf-ncgr I think I'll leave it as is for the time being then. Closing.
