### ISSUE TITLE
improve load times

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/lis_context_viewer#22]
like we tried to do once before- only better!

**Comment by alancleary** [comment]
As per our discussion, the slow load times may be due to the huge number of scripts being loaded by a limited number of FTP connections. This could possibly be alleviated by leveraging [webpack](https://webpack.github.io/) in the build.

**Comment by alancleary** [comment]
Functionally complete in 595ef695ab9c8b326b1f56bdad2d2a34adc4b4ce. Loose ends to follow.
