### ISSUE TITLE
Micro-Track search, filter, and ordering

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/lis_context_viewer#226]
Before the unified gene view, micro-track search, filtering, and ordering was done on a "global" level, that is, the filters were applied to all tracks in the view. Now that tracks are being clustered into their own sub-views, this global approach doesn't make as much sense. For now, implement these on a per sub-view basis and omit them from the URL query string parameters.

**Comment by adf-ncgr** [comment]
@alancleary agreed that it doesn't make as much sense, but wondering whether it might still make enough sense to justify retaining a global level option that can be used in the URL. I see it as being certainly useful for the arguably more typical case (to date: possibly a tautology) where there's only a single subview. However, even in the event that we have multiple subviews, I could see it being typical to want to filter them/sort them consistently. And I'm not sure searching in one subview and leaving the others as they were is a use case that has much reason to justify having independent widgets per subview; offhand at least, it seems like a search initiates a view/set of views, but probably doesn't want to get offered as something other than an entry point or global reset of the view-set. NB: I haven't thought any of this through carefully, just reacting to the loss of URL query strings: they're just so restful...

**Comment by alancleary** [comment]
I think we could implement these globally for now, if only to ease transition until we have a more clear path forward.

**Comment by alancleary** [comment]
Track filtering and ordering were reimplemented in commit 9f43e38a462067f554bb1fcd19b48840a33001a7. Reimplementing the search functionality in a much more robust way is the focus of epic #212 and is out of scope for the issue. Closing.
