### ISSUE TITLE
Update Instructions Page

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/lis_context_viewer#252]
The instructions page needs to be updated now that the search and multi views have been combined into a single gene view. Also, the screenshots need to be updated to show the new Golden Layout UI instead of the SplitJS UI.

**Comment by alancleary** [comment]
@adf-ncgr Is there a particular example you would like included as the default screenshot?

**Comment by adf-ncgr** [comment]
I'm tempted to say this one
![image](https://user-images.githubusercontent.com/2009605/82247415-957a6700-9903-11ea-9377-eaf5640affb5.png)
but I should probably think about it a bit more

**Comment by alancleary** [comment]
That's certainly an interesting example. Maybe something with a smaller neighborhood will be better for the uninitiated?

**Comment by alancleary** [comment]
The main structure of the page was revised in commit 428830d47b70c7d9da00947eb629e1a2c2aca693. The content explaining the viewer still needs to be updated. @adf-ncgr Do you think it would be worth replicating the constructive explanation from the AgBioData presentation? i.e. this is a query gene -> this is a query track -> this is a micro-synteny search -> etc.

**Comment by alancleary** [comment]
P.S. The "Take the Tour" silo needs to be removed but the layout feels a little awkward with only two silos. @adf-ncgr Any thoughts on a silo would could put in its place until we get tours up and running again? It wouldn't be the end of the world if there was only two silos for now.

**Comment by cann0010** [comment]
I'll mention something that's been a bit of an impediment/irritant for me on the GCV Instructions pages: in the "Search Now" text entry box, the examples seem like they should be helpful ("e.g. phavu.Phvul.002G100400 or glyma.Wm82.gnm4.ann1.Glyma.02G028300"), but I am not able to select that text to paste either of the examples, and if I try to type either example directly, the example text evaporates. So, I end up either having to go elsewhere to find a gene to enter, or trying to memorize the string and type from memory, or typing out the name in a text editor on the side and the pasting that into the text-entry box.
Also ... at http://dev.lis.ncgr.org:50011/epic_search/gcv/instructions, the example soybean gene (glyma.Wm82.gnm4.ann1.Glyma.02G028300) fails with the default LIS source. It seems to work only with "Glycine pangenes" as a source.

**Comment by alancleary** [comment]
Thanks @cann0010. You're not the first person to be irritated by this. I'll update the page so that the examples are under the search widget so you can copy-paste them.

**Comment by adf-ncgr** [comment]
> Do you think it would be worth replicating the constructive explanation from the AgBioData presentation? i.e. this is a query gene -> this is a query track -> this is a micro-synteny search -> etc.

sounds reasonable, although I guess eventually some of this will occur in the context of a user tour, so maybe just keeping it very high level (as I think your presentation did)

**Comment by adf-ncgr** [comment]
> Any thoughts on a silo would could put in its place until we get tours up and running again? It wouldn't be the end of the world if there was only two silos for now.

agreed that it's not the end of the world to have sparse silos; I would note that both the Read the Docs and Developer Zone silos currently point to the same place: https://github.com/legumeinfo/lis_context_viewer/wiki
not sure that was the intent.

**Comment by adf-ncgr** [comment]
> Also ... at http://dev.lis.ncgr.org:50011/epic_search/gcv/instructions, the example soybean gene (glyma.Wm82.gnm4.ann1.Glyma.02G028300) fails with the default LIS source. It seems to work only with "Glycine pangenes" as a source.

that's correct. perhaps I should not have included it in the ghost text (I am one of the people who has been irked by its incorporeal nature in the past). Anyway, this is all stuff to be discussed soon in terms of how a soybase-specific instance should be configured

**Comment by alancleary** [comment]
The description of the GCV was updated in commit c9b2c4a6df7360a9afef56ce70a0d517bbbb2514. The images in the description still need to be updated.

**Comment by adf-ncgr** [comment]
this sounds like my cue to give you a better screenshot than my cowpea magnum opus

**Comment by alancleary** [comment]
@adf-ncgr Yes. And ideally it would include an interesting micro-synteny structural variation (tandem duplication, inversion, and/or copy-number variation), local plot, global plot, reference macro-synteny, and circos macro-synteny. Though I suppose a different example could be used for each of these if finding one example with all of them is too tall an order. Good luck!

**Comment by alancleary** [comment]
The search widget input placeholder text was converted to copy-pastable help text in commit 5219b8a01ad988c92a1be2fe9c2aaf92a74b0961. Gripe no more, @cann0010 and @adf-ncgr!

**Comment by adf-ncgr** [comment]
I'll stop griping the day they make the official release ;) 
(and when they pry the wooden teeth from my rigor-mortis-stiff but still griping gums....)

**Comment by adf-ncgr** [comment]
@alancleary working on finding a close-to-ideal example for a screenshot showing off some features of interest. A question that came up as I am looking at refining the view is whether GCV1 capabilities to apply to the macroview the "microsynteny-order" or "microsynteny-only" options are somewhere in GCV2 that I'm not seeing or are these in need of an issue (non-blocking)?

**Comment by alancleary** [comment]
@adf-ncgr It needs an issue.

**Comment by adf-ncgr** [comment]
OK will put one in. How does this screenshot appeal to your aesthetic sensibility? 
![image](https://user-images.githubusercontent.com/2009605/82485579-e53e6700-9a98-11ea-9816-9732d0469020.png)


right hand global dotplot is showing a region of a soybean chromosome (Gm12) that is syntenic to itself (ancient duplication + subsequent rearrangements), while right hand dotplot shows some of the CNV apparent in two of the mult-aligned lines. An inversion can be seen in one of the tracks brought in from the search against the multi-model. There's something of a biological story here, but it's primarily a comparative genomics use case.

**Comment by adf-ncgr** [comment]
PS. I have no idea why I get that warning for "Positions" but I guess it illustrates that not everything is always green and checky.

**Comment by alancleary** [comment]
@adf-ncgr Looks great! Do you mind providing a link so I can crop different screenshots for each of the sections in the tutorial?

**Comment by adf-ncgr** [comment]
http://dev.lis.ncgr.org:50011/epic_search/gcv/gene;lis=glyma.Glyma.12G177400,vigun.Vigun05g245500,glyma.Glyma.13G323300,phavu.Phvul.005G131800,glyma.Glyma.11G194800,vigun.Vigun11g137100,phavu.Phvul.011G083900,glyma.Glyma.12G079300?algorithm=repeat&match=10&mismatch=-1&gap=-1&score=30&threshold=25&bmatched=20&bintermediate=10&bmask=10&linkage=average&cthreshold=100&neighbors=20&matched=0.3&intermediate=10&sources=lis&bregexp=glyma%7Cvigun%7Cphavu&border=chromosome&regexp=lup&order=distance

**Comment by adf-ncgr** [comment]
tut(orial) your horn, lad!

**Comment by alancleary** [comment]
Updated the documentation link in commit 000b27d86a54f09a92f511729da8c782f18b25f1.

**Comment by alancleary** [comment]
The instructions page images and their descriptions were updated in commit 003352f668f62830bbb6ac39d4ac78e37f4c85ec.

@adf-ncgr These were based on the example you provided. Feel free to revise the image captions via the config file as you see fit.

**Comment by alancleary** [comment]
Th default examples in the config file were updated in commit aac9d8f9f487c7f087c956658087f0cd6350ec45.

**Comment by alancleary** [comment]
Unless someone thinks the captions for the screenshots need to be updated to be more legume specific (@adf-ncgr?), then I think this is done.

**Comment by adf-ncgr** [comment]
sorry @alancleary I've been remiss; let me try to take a quick look.

**Comment by adf-ncgr** [comment]
boy, you've done a lot of nice work on that since I last git pulled. looks very sharp! Do you want me to try to add any of my trademark cheekiness to the captions?

**Comment by alancleary** [comment]
No cheekiness necessary. I just wanted to be sure not explicitly mentioning legumes or specific variation that's happening in the examples is ok with you (or anyone else that cares).

**Comment by adf-ncgr** [comment]
OK I'll keep my cheekiness in check. I will have a few minor changes to make though.
Does the caption associated with gcvScreenshot actually appear in the page? The content looks outdated, but I don't actually see the text in the page

**Comment by alancleary** [comment]
> Does the caption associated with gcvScreenshot actually appear in the page? The content looks outdated, but I don't actually see the text in the page

No. I thought it would be weird if the image associated with the title had a caption. At some point after the version 2 release I plan to make clicking on any image open a lightbox containing a higher resolution copy of the image and its caption. This means clicking on the title image will show a caption, so go ahead and add one if you want.

**Comment by adf-ncgr** [comment]
sounds good and will do. One question regarding actual functionality. I see that in the screenshot I sent, the query tracks are not exactly ordered as I might have wanted/expected with the sort by edit distance, though I guess I am not sure exactly what to expect if edit distance is being defined against the HMM. Still, it seems a bit odd that the ones that most resemble each other would not end up together (which is what I'd want); in theory, I know I could group them by clustering, but then they wouldn't get aligned together. Any thoughts ?(other than that adf must never actually want release 2.0 to happen?)

**Comment by alancleary** [comment]
That may have been from me fidgeting with the view before taking screenshots. If you really want the other ordering I can change it.

**Comment by adf-ncgr** [comment]
I'm pretty sure it was not from fidgeting as I went back to the link I ha sent you and got the same thing. I'm not sure the tool is currently able to give me the ordering I actually want. We are admitttedly in nice-to-have land with this, but I think most biologists would agree that it's not merely an aesthetic concern in this case. We could just put it on the "wait until users can define their own ordering" pile (I think there's an existing issue for this from way back).

**Comment by adf-ncgr** [comment]
captions updated in a1c12f4
will defer to @alancleary if he wants to close the issue or try to satisfy my impossible demands for ever greater biological idealism.

**Comment by adf-ncgr** [comment]
@alancleary I should probably have made more explicit in my above ramblings that the underlying biological ideal to which I'm aspiring would be to have a sort order that would more or less reflect the order you'd expect to see were you to look at individual gene trees for genes common to all of the query tracks. I'm sure this can't be realize fully in practice with GCV alone because I think we've abstracted away too much to give full resolution of the relationships, but I was hoping obvious coarse-grained relationships might be feasible. That said, another "cool for future" use case would be to get service-based or broadcast channel-based ordering from an actual gene tree (which we may also have discussed in the past) which would make the current "coarse-grained ideal" moot. So, I think I'm giving you ample justification to defer utopia to another day.

**Comment by alancleary** [comment]
I think the only coarse grained ordering/trees we can do without bringing in additional information is via the agglomerative hierarchical clustering that's being used for the query tracks, which would probably be pretty easy to do since the only new code that would really need to be written is a visualization if we wanted it. Definitely worth pursuing after the release.

**Comment by adf-ncgr** [comment]
OK, sounds good; I think you are suggesting that basically we could apply the same clustering technique but "within group" after the groups have initially been defined (in the case of the screenshot there is just the one group). This second-round clustering could be used to define within-group ordering. Not sure why a new vis would be needed- to show the underlying clusters? a nice to have, but definitely not necessary for starters in my book. thanks for being ever indulgent to my inner biologist.

**Comment by alancleary** [comment]
All the to-dos for this issue have been done, plus the loading bloat caused by the images has been addressed inn #301. Closing.
