### ISSUE TITLE
no-longer-basic view should merge tracks that are overlapping instances of same region

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/lis_context_viewer#26]
classic case is when the focus gene is tandemly duplicated. in olden days it was arguable that both genes should get to have a turn in the spotlight of the central slot. but now that alignment is taking place that argument no longer holds. I don't see a compelling reason not to make one longer track by merging tracks that have some gene instance(s) in common.

**Comment by alancleary** [comment]
Done in b35af597b6a60595fc955db31ebe0b5b663f3e0a
