### ISSUE TITLE
maximize gives oddly transparent views

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/lis_context_viewer#263]
I'm not offhand sure why one would use the goldenlayout maximize option (though not saying I won't want to someday); however, currently invoking it seems to produce a semi-psychedelic effect, as in the screenshot below. perhaps just an issue of things needing to have an opaque base canvas (or whatever the appropriate term is here)?

![image](https://user-images.githubusercontent.com/2009605/73327561-afd4eb80-4213-11ea-888d-dad64067effd.png)

**Comment by alancleary** [comment]
Fixed in commit 989b74446ede77713edc718af5949df94fb7f4b8.
