### ISSUE TITLE
popping view out into new window sometimes gives 403 Forbidden errors

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/lis_context_viewer#264]
this seems likely to be on my end regarding the apache conf, but noting as an issue nevertheless and will self assign; this works (URL reached via the internally generated link after an initial single gene search) :
http://dev.lis.ncgr.org:50011/epic_search/gcv/gene;lis=phavu.Phvul.002G084200,glyma.Glyma.02G108400,glyma.Glyma.01G048800,glyma.Glyma.01G048900,lupan.Lup008649,cajca.C.cajan_30495,araip.Araip.6C94R,lotja.Lj2g3v1277760,vigra.Vradi11g10400,vigan.Vang0065s00140,tripr.Tp57577_TGAC_v2_gene39183,cicar.CDCFrontier.Ca_18075,vigun.Vigun02g059600

but a subsequent reload fails with 403, as does the attempt to pop out into a new window:

http://dev.lis.ncgr.org:50011/epic_search/gcv/gene;lis=phavu.Phvul.002G084200,glyma.Glyma.02G108400,glyma.Glyma.01G048800,glyma.Glyma.01G048900,lupan.Lup008649,cajca.C.cajan_30495,araip.Araip.6C94R,lotja.Lj2g3v1277760,vigra.Vradi11g10400,vigan.Vang0065s00140,tripr.Tp57577_TGAC_v2_gene39183,cicar.CDCFrontier.Ca_18075,vigun.Vigun02g059600?gl-window=gl-window-config-2wbt3h1pqdy

and it can't be loaded directly either; so, maybe it is not the apache config end- have you seen this @alancleary ? I'm happy to dive in to config hell if it is working fine under the ng-serve.

**Comment by adf-ncgr** [comment]
now thinking this may be a case of exceeding server-side URL character limits (even though those URLs don't seem egregiously long to me); a more modest list of genes works fine in both scenarios, e.g.:
http://dev.lis.ncgr.org:50011/epic_search/gcv/gene;lis=vigun.Vigun09g073800,vigan.Vang09g02380,phavu.Phvul.009G188000

**Comment by alancleary** [comment]
I was just writing you a somewhat technical response:

I was able to (re)load the first link. The second link belongs to the popped out window, as indicated by the `gl-window=gl-window-config-2wbt3h1pqdy` query string parameter. I wasn't able to load it, though I was able to load pop outs from within the GCV. Reloading these pop outs broke in the same way as when I tried to load the second link.

The error indicates that the layout's stack is undefined when a pop out is loaded directly or reloaded. Poking around in the GoldenLayout code, I see that when a pop out is created from an existing GoldenLayout, it programmatically uses that layout's stack configuration to bootstrap that of the pop out. When a pop out is loaded directly (or reloaded), the pop out is not created programmatically and therefore the original layout's stack configuration cannot be used. In this case, the pop out falls back to the GCV's default stack configuration. So what I think is happening is the pop out is trying to add the popped out item to GCV's configuration before it has even been initialized. I'm not sure how to handle this but I don't think it should be consider a version 2 blocker.

**Comment by adf-ncgr** [comment]
do you mean you were able to load it in the context of ng-serve? (because I still get the 403 error when loading it from the apache site). I am not sure I have grasped paragraph 3, but that's probably OK. I'm not concerned about being able to reload the pop out URLs, but mildly concerned if pop outs are not functioning reliably in their "native" contexts. Not concerned enough to put a kibosh on v2.0 but we might just consider disabling that option (if that's easy) until such time as "we" have a solution (if I understood you to mean that pop-outs aren't always working for you, as I believe they were not for me); but, if everything except the reloading was really just a 403 due to apache conf, then nevermind.

**Comment by adf-ncgr** [comment]
PS. having done the due-diligence google, I see that default URL length limits under apache are much longer than the paltry example giving me trouble, and the expected error is different; so while still possibly a config issue, probably not the conclusion I jumped to hastily above

**Comment by alancleary** [comment]
@adf-ncgr Correct; I was able to run it with ng serve.

I think disabling pop outs for now is a good idea. You can effectively pop out using the broadcast channel anyway, so it's not like we're loosing any functionality.

**Comment by alancleary** [comment]
The pop out button was disabled in commit 989b74446ede77713edc718af5949df94fb7f4b8. I'll close this ticket for now, though I'm OK with opening it later if/when we want to revisit pop out functionality.
