### ISSUE TITLE
Rename basic (and search?) view

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/lis_context_viewer#27]
It seems the basic view is no longer aptly named. Perhaps "pan"? Also, it might be worth renaming the search view to something more distinguishing/related, such as "pairwise".

**Comment by alancleary** [comment]
Pan!

**Comment by adf-ncgr** [comment]
guess we've made the decision so I'm going to Stage this issue so that we don't forget to
immortalize it in the URL scheme of our next release.

**Comment by alancleary** [comment]
Done in commit e86b80b11c43a9b8814adc997df7a1c55457e8f1
