### ISSUE TITLE
can invocation of the multiview from within the app properly assign query genes to their sources?

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/lis_context_viewer#278]
the ever helpful pipeline monitoring system clued me into the fact that when "View genes in multi-alignment view" is chosen on a set of genes, the Cartesian product of genes X sources is being formed, leading to some successes, and some failures. The end result is that you get what you wanted, but the pipeline status is a bit confusing and it is certainly less efficient than it would be otherwise.

![image](https://user-images.githubusercontent.com/2009605/78728880-c83d4280-78f5-11ea-8651-2922d1140bb3.png)

**Comment by alancleary** [comment]
@adf-ncgr Short answer: no. Longer answer: That's what was previously being done but I deemed the functionality to be part of the imminent search functionality. The Cartesian product was a temporary solution to support backward compatibility. As you've pointed out, the pipeline really draws attention to it...

**Comment by adf-ncgr** [comment]
I would have thought that if the internal datamodel tracks which source has returned a given track then it could be done fairly trivially when the URL is constructed from within the app. But I agree that for gene names supplied from without, it's a different ballgame altogether- "
"imminent search functionality".

**Comment by alancleary** [comment]
@adf-ncgr Whoops. I was multitasking and didn't comprehend the "within the app" bit. As you've pointed out, the app has the data in hand that it needs to properly structure "multi" URLs. So, yes, multi view URLs should be properly assigned from within the app.

I'll update the ticket to make this a feature request.

**Comment by adf-ncgr** [comment]
sounds good.

**Comment by alancleary** [comment]
Done int commit 8d84d72ec916133db5d2a696fff5ad906ae40c8d. Closing.
