### ISSUE TITLE
GCV: Include white genes in legend

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/lis_context_viewer#28]
<p>It is not at all apparent why some micro-synteny gene glyphs are white and some a white with dash outlines. Include these in the legend. Moving the highlighted gene family to the top may help as well.</p>
<i>[LEGUME-697] created by alancleary</i>

**Comment by alancleary** [comment]
Commit 35765857591c3e78de520961c2885c9fcbcfba34 added entries to the micro-synteny legend for "Singletons" and "Orphans". Now the question is do we remove the links to view the phylotree for the selected family in the left slider since one of these represents no gene family and the other represents several?!

**Comment by adf-ncgr** [comment]
not sure I completely understand your question- a "singleton" is only a singleton with respect to the current view, but the gene family it belongs to should be much like any other gene family, so no
reason that I can see to alter their behavior. "Orphans" on the other hand I agree should not have a phylotree link since there is nothing to link to in that case.

**Comment by alancleary** [comment]
I'm referring to the slider that appears when you click on a gene family in the micro-synteny legend. Until now, each key in the legend has represented a single gene family, so we hard coded a "View genes in phylogram" link into the slider. Now that we've added keys for orphan and singleton genes, the link can't handle these scenarios. In the case of the orphans, I think supressing the link will suffice. The question is, in the case of the singleton genes, which all belong to different gene families, do we want to simply suppress the link or do something else, such as giving each gene its own link?

**Comment by adf-ncgr** [comment]
Oh, I get it now; there is a single legend entry representing multiple gene families so the difficulty is to know which one could be meant on click. I think I agree it makes sense to suppress linking in this case too- users can click on individual genes to get links to their families. AlthoughI suppose one might make some argument that it could be of interest to see listed all of the singleton families present, if one was interested in exploring things that are unique and possibly functionally differentiating. This might become even more interesting when we add in the metadata-based capabilities to include functional descriptors of the families. I guess we will talk in <10 minutes so can weigh the pros/cons and try to come to a decision then.

**Comment by alancleary** [comment]
Commit f7bf09d9d67a8e236822ec9b3f82a2b425197bce add "Singletons" and "Orphans" to the basic micro-synteny legend. Commit 0fd45ae34a02b3707c60be19dc00dc6b7be05f32 suppressed the "View genes in phylogram" link when either of these keys is selected.
