### ISSUE TITLE
Update the server

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/lis_context_viewer#281]
The server currently uses Python 2 and Django 1.11. Python 2 reached end of life on January 1 and Django 1.11 reached end of support on April 1. It is critical that these are updated before release!

**Comment by alancleary** [comment]
I forgot to consider the fact that in Python 3 functions that take an iterable as an argument (map, filter, zip, etc) return an iterator instead of a list, as in Python 2. Unfortunately this breaks a lot of services code because the results of these functions are often iterated multiple times and an iterator can only be iterated once.

Fixing this is as simple as using the single iteration to instantiate a list that can be iterated as many times as necessary, but a lot of code is affected. I'll update the estimate on this issue to take this into account.

**Comment by adf-ncgr** [comment]
sounds like the perfect job for a minion...

**Comment by alancleary** [comment]
Done in commit a1685507cfa4dec43c2ce5cd4d0802cd8d92be1b. Closing.
