### ISSUE TITLE
some components need scrollbars when content is larger than their size

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/lis_context_viewer#285]
an example is the gene family detail, which can grow long vertically when there's a local cluster of the same gene family conserved across several genomes.

**Comment by alancleary** [comment]
@adf-ncgr Do you know of any other components that are affected?

**Comment by adf-ncgr** [comment]
I think all the details panes (track, gene, family) have this issue. haven't notice it elsewhere

**Comment by alancleary** [comment]
OK. Thanks!

**Comment by alancleary** [comment]
Done in commit 6e73c6cf265a51ffa7e092d75e30c30082a69987. Closing.
