### ISSUE TITLE
"Search for similar contexts" link needs to be updated

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/lis_context_viewer#288]

**Comment by adf-ncgr** [comment]
currently when a gene detail is requested the target of the search link looks something like this:
/search/lis/undefined?
I'm going to assign it to myself and see if I can score a GCV2.0 minor assist.

**Comment by adf-ncgr** [comment]
fixed in 954c47b 
(and adf needs to learn how to clear his browser cache more effectively)

**Comment by alancleary** [comment]
@adf-ncgr I see you used the old search URL format, which is in legacy mode now. It might be worth using the new URL with matrix string parameters for longevity.

**Comment by adf-ncgr** [comment]
sure, I was just following what was there, but did notice that it ended up in some LegacyRouterGuard (or some such). happy to change it.

**Comment by adf-ncgr** [comment]
fixed more properly in c3be32b
