### ISSUE TITLE
GCV: Contextmenu

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/lis_context_viewer#29]
<p>Requiring that users right-click to reveal the viewer contextmenu effectively makes it a hidden feature. Let's put this content front and center by making it a discrete but apparent menu in every viewer's container.</p>
<i>[LEGUME-694] created by alancleary</i>

**Comment by alancleary** [comment]
Fixed in 02d93356ced29955736a26cd1ebc04a523700d54
