### ISSUE TITLE
dotplot axis labeling 

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/lis_context_viewer#294]
I think there's some confusion with labeling that is probably easily addressed (I hope).
see example screenshot below, where vigun.CB5_2.gnm1.chr3:31562985-36874990 is the
reference span, which has the coordinates appearing on the y-axis but the chromosome label appearing on the x-axis. in some sense the chromosome label might be considered redundant with the information presented in the goldenlayout tab title, though I think there are probably good reasons for including labels for both axes in the actual plot. Probably when dotplots applied only to single-reference contexts it made more sense to only show one, but now we can't rely on that and in any case we oughtn't label the x axis with what's displayed on the y axis. 

![image](https://user-images.githubusercontent.com/2009605/81232973-1efc7180-8fb3-11ea-9a47-28496a979cd7.png)

**Comment by alancleary** [comment]
Commit 7cbe62d32a870bdf99a8835be02329d940d3862d fixed the mislabeling bug and also added a label to the y-axis.
