### ISSUE TITLE
views should "unload" tracks when sources are deselected

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/lis_context_viewer#295]
I mentioned this in a meeting earlier in the week, just getting around to filing the issue. 

Here's a brief description that I think will allow you to reproduce it:
a) start with /gene;vigna=vigun.IT97K-499-35.gnm1.ann2.Vigun11g008150.v1.2?algorithm=repeat&match=10&mismatch=-1&gap=-1&score=30&threshold=90&bmatched=70&bintermediate=10&bmask=10&linkage=average&cthreshold=20&neighbors=30&matched=0.33&intermediate=25&sources=vigna,vigan&bregexp=vig&border=chromosome&regexp=&order=chromosome
b) deselect the Vigna unguiculata source and submit; in my experience nothing changes, though my expectation would be that all result tracks with the exception of the one adzuki bean track (vigan.Shumari) should be removed.

**Comment by alancleary** [comment]
Fixed in commit 2a88fde02cc11b40bb824e8e5f6a0cf71b0821fd. @adf-ncgr Apparently the vigna services endpoint I have doesn't contain the gene from your example but it seems to be behaving as expected in other contexts. Feel free to reopen the issue if it isn't working for your specific example.
