### ISSUE TITLE
GCV: Basic phylogram

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/lis_context_viewer#30]
<p>This is an experimental feature.</p>

<p>Landing on the Basic view of the Genome Context Viewer from an LIS phylogram can be disorienting if you've never encountered the Genome Context Viewer. To make it more apparent what is happening a phylogram should be placed next to the micro-synteny viewer such that the leaves (genes) align with their corresponding tracks.</p>
<i>[LEGUME-692] created by alancleary</i>

**Comment by alancleary** [comment]
This issue is stale. Closing.
