### ISSUE TITLE
Change repository description

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/lis_context_viewer#300]
I was hoping to change the repository description prior to release but it appears I don't have permission to access its settings. In lieu of being given more privileges than I care to have, I humbly ask that one of the privileged among us update the description for me. This is what I had in mind, though I won't be offended if the privileged uses their status to take liberties: "A web-app for the visual exploration of multiple annotated genomes using microsynteny"

**Comment by adf-ncgr** [comment]
OK, I added macrosynteny as well. did you not want to say something about "FEDERATING GENOMES (WITH LOVE)" ?

**Comment by adf-ncgr** [comment]
PS. do you think we ought to change the name of the repository as well?

**Comment by alancleary** [comment]
> OK, I added macrosynteny as well. did you not want to say something about "FEDERATING GENOMES (WITH LOVE)" ?

That's the best idea you've ever had! Seriously, I think the description should be "Federating genome with love (and functional annotations)"

**Comment by alancleary** [comment]
> PS. do you think we ought to change the name of the repository as well?

I think we ought to change it but not now. Mostly because I'm not sure if we want to separate the client and server into different repos as we move into microservices. Whatever we end up doing, we'll need to keep the original repo for posterity, i.e. we used that URL in the GCV manuscript.

**Comment by adf-ncgr** [comment]
OK, happy to wait and I agree that future separation seems likely if only to support the theoretical possibility of mix-and-match between client and the many possible server implementations (I'm going to start one in Lua any day now).

BTW, I know you're serious that it's the best idea I ever had but are you serious you want to add that to the description? I'll do it if you really are...

**Comment by alancleary** [comment]
I am serious. I think we should do it so long as you and @cann0010 are cool with it and think it wouldn't bother current or potential funding agencies. When the repo comes up in a Google search the description only appears in the title and it's truncated. I'm also working on adding a screenshot to the very top of the readme so despite the cheeky description, people will get the idea as soon as they land on the page.

**Comment by adf-ncgr** [comment]
@cann0010 loves genomes as much or more than the next guy so I imagine he'll be cool with it. He may even be cool season. But I will let him speak for himself.

**Comment by cann0010** [comment]
Not precisely sure what the proposal is, but I'm probably cool with it. It's easy. All you need is love.

**Comment by adf-ncgr** [comment]
> All you need is love.

and functional annotations. 
closing
