### ISSUE TITLE
The source dropdown for search widget on instructions page is broken

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/lis_context_viewer#313]
There's an error in the console: "Bootstrap's dropdowns require Popper.js (https://popper.js.org/)" Which is weird because Popper.js is installed, albeit via Tippy.js and a newer version than what is required by Bootstrap, but the same dropdown works for the expandable dropdown widget in the navbar.

Debug and fix this!

**Comment by adf-ncgr** [comment]
I thought its disappearing was by design- so that the new search would be federated across all providers.The search seems to work that way. 
I also don't seem to get the error you refer to here http://dev.lis.ncgr.org:50011/search/gcv/instructions
but I could be misunderstanding your description

**Comment by alancleary** [comment]
@adf-ncgr The dropdown is opened by clicking the down-carrot between the text input and the "search" button. This is broken on the search widget on the instructions page underneath the "Search Now!" text. The search widget in the navbar (revealed by clicking the magnifying glass search icon), however, works just fine.

**Comment by adf-ncgr** [comment]
got it- it is as you say. Well, if it becomes a time-suck, we can revisit whether it's worth the effort. thanks for cleary-fying

**Comment by alancleary** [comment]
Fixed in commit 6609fc0c6952eb5849e88ebefe03b3483f656387.
