### ISSUE TITLE
Service discovery

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/lis_context_viewer#321]
Inter-service communication is done via gRPC. If a service wants to make an RPC request, it must know the address of the service to send the request to. This address can be hard-coded at run-time or read from an environment variable. The latter actually re-reads the environment variable every time a request is sent in case its value has changed. This is to facilitate service discovery, e.g. if requests are being load balanced across more than one version of a service or if a service has been restarted, etc. It would be nice if the Docker Compose in issue #320 could optionally include or utilize a service discovery service.

**Comment by nathanweeks** [comment]
Could the default [Docker Compose networking](https://docs.docker.com/compose/networking/) be considered good enough for service discovery?
>  By default Compose sets up a single network for your app. Each container for a service joins the default network and is both reachable by other containers on that network, and discoverable by them at a hostname identical to the container name.

Regarding load balancing: I think this would involve specifying the number of instances using the [scale](https://docs.docker.com/compose/compose-file/compose-file-v2/#scale) parameter, and putting a load balancer in front (nginx for HTTP, or more likely [Traefik](https://docs.traefik.io/routing/providers/docker/) for HTTP and gRPC).

**Comment by alancleary** [comment]
> Could the default Docker Compose networking be considered good enough for service discovery?

Yes. I think this is very much in compliance with Occam's razor. Great suggestion!

>Regarding load balancing: I think this would involve specifying the number of instances using the scale parameter, and putting a load balancer in front (nginx for HTTP, or more likely Traefik for HTTP and gRPC).

I think load balancing may be out of scope here. While it's nice to a have, I don't think it should be included in the turn key solution provided by the repository. Of course my opinion is bound by this repository; if you feel like introducing it in the LIS, etc deployments I certainly won't object.
