### ISSUE TITLE
GCV: Sticky alerts

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/lis_context_viewer#36]
<p>It would be nice to have some (sticky) alerts return after other, more temporal alerts have been shown. For example, it would be nice to have the context search result statistics reappear after an alert saying that the gene links service failed.</p>
<i>[LEGUME-682] created by alancleary</i>

**Comment by alancleary** [comment]
This has been effectively done with the move to source specific alerts within each viewer. See commits 94cefd82e91817c4139b5485b6cec8dd9ab4f4a0 and 31e44838e0db219025df2a2761650126ac85c89e for examples. Closing.
