### ISSUE TITLE
intergenic segments being (mis)labeled as negative distances

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/lis_context_viewer#38]
<p>the only case I can think of where it seems valid to call an intergenic distance negative is in the<br/>
case of overlapping gene models.</p>

<p>this example has at least a few tracks that exhibit the behavior:<br/>
<a href="http://legumeinfo.org/lis_context_viewer/index.html#/search/lis/glyma.Glyma.06G017900?regexp=&order=chromosome&neighbors=5&sources=lis&matched=2&intermediate=2&algorithm=repeat&match=3&mismatch=-1&gap=-1&score=25&threshold=10" class="external-link" rel="nofollow">http://legumeinfo.org/lis_context_viewer/index.html#/search/lis/glyma.Glyma.06G017900?regexp=&order=chromosome&neighbors=5&sources=lis&matched=2&intermediate=2&algorithm=repeat&match=3&mismatch=-1&gap=-1&score=25&threshold=10</a></p>

<p>thought it might be a case of a track aligned in reverse-orientation, but not clear that this is the case. </p>
<i>[LEGUME-680] created by adf_ncgr</i>

**Comment by alancleary** [comment]
Fixed in b264e0b49db964c87e89fda446b4052a212b3981
