### ISSUE TITLE
GCV: avoid "crossed swords" labeling effect

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/lis_context_viewer#39]
<p>maybe rotating clockwise from noon for the labels that run upwards would solve this:<br/>
 <span class="image-wrap" style=""><a id="13100_thumb" href="https://legume.atlassian.net/secure/attachment/13100/13100_image-2017-01-11-08-43-18-035.png" title="image-2017-01-11-08-43-18-035.png" file-preview-type="image" file-preview-id="13100" file-preview-title="image-2017-01-11-08-43-18-035.png"><jira-attachment-thumbnail url="https://legume.atlassian.net/secure/thumbnail/13100/image-2017-01-11-08-43-18-035.png?default=false" jira-url="https://legume.atlassian.net/secure/thumbnail/13100/image-2017-01-11-08-43-18-035.png" filename="image-2017-01-11-08-43-18-035.png"><img src="https://legume.atlassian.net/secure/thumbnail/13100/image-2017-01-11-08-43-18-035.png" data-attachment-name="image-2017-01-11-08-43-18-035.png" data-attachment-type="thumbnail" data-media-services-id="c8012635-3070-4817-b6fb-95ecff3fa9b2" data-media-services-type="file" style="border: 0px solid black" /></jira-attachment-thumbnail></a></span> </p>
<i>[LEGUME-678] created by adf_ncgr</i>

**Comment by adf-ncgr** [comment]
does this really belong to the Metadata Epic?

**Comment by alancleary** [comment]
It appears this issue was already addressed at some point. Closing...
