### ISSUE TITLE
does it make sense to have "outliers" in global dotplot?

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/lis_context_viewer#6]
The global dotplot retains the "Outliers" label above the graph, but does not seem to actually display any content there. It seems a little less useful in the global context, just because the "holes" that it highlights in a local segment are more likely to get "filled in" by a non-local member of the same gene family, although only if the non-local member is on the same chromosome, which seems a little arbitrary. I guess we should either:
a) suppress the Outliers label on the global plot if we decide it doesn't make sense
b) make it functional (I'm pretty sure it should at least retain the genes that are unassigned to
families when you go from local to global, since those by definition can't be "filled in")

probably some more thinking to do about the utility of outliers before making this decision

**Comment by alancleary** [comment]
When upgrading to D3 version 4, the dot plot viewer was reimplemented (commit 78b54ab8001e7289e7b630c0482f5de7296dd88c). In the process, the outliers were removed, more due to time constraints than anything. So apparently we're going with option (a), at least for now. Closing.
