### ISSUE TITLE
Family based search

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/lis_context_viewer#62]
In both the basic and search views, the user can click a family in the micro-synteny legend to reveal a slider containing information and links relevant to the selected family. Add a link to this slider that loads a basic view containing the family-members present in the current view.

**Comment by adf-ncgr** [comment]
I did a simple first step on this in 062def0 ; but just realized it has some issues- seems like it may suffer from the same underlying problem as in #16 (can get it to work if opened in new tab, but not in same page app mode); also, it doesn't always work properly when there are multiple sources of track data (it must just be getting the default datasource and using that- I probably didn't think to specify anything but the list of genes- but not sure I should have to either, seems like the parameter last-value memory should help? )

**Comment by alancleary** [comment]
#16 has been fixed and closed.

The GCV notices when required query parameters are missing from the url and loads the most recent values used from the current application state. This includes sources. As such, I haven't been able to replicate sources not being passed correctly between views. I believe this may be because the link in question used to reference index.html, rather than just the Angular fragment of the url (fixed in 6de753987bdec539932c780abe3cff49cc9a9710). If this indeed seems to have fixed the problem then I think we can close this issue.

**Comment by adf-ncgr** [comment]
verified as fixed (leave the nail in the coffin!)
