### ISSUE TITLE
outliers display seems to only function on initial vis. of local dotplot

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/lis_context_viewer#7]
If you have a local plot with outliers, and then "zoom" using the brush, the outliers disappear, even when it seems they should be in view. In fact, if you then clear brush, they do not return to the display until you refresh by clicking on the local tab of the dotplot widget. seems like a bug.

**Comment by alancleary** [comment]
This no longer seems to be an issue. Closing...
