### ISSUE TITLE
The micro-synteny regular expression and sorting filters appear to be broken in both the basic and search views

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/lis_context_viewer#73]

**Comment by adf-ncgr** [comment]
can you also check to see if sorting in the search view is broken? seems to be for me but that could also be the other things plaguing my setup...

**Comment by alancleary** [comment]
Indeed, sorting is also broken. Updating title...

**Comment by alancleary** [comment]
Done in e8a3df7ac52819bb44e48f57c66f912123083efb
