### ISSUE TITLE
Add sorting to the basic view?

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/lis_context_viewer#74]
Now that tracks are being aligned, they have scores. Does it make sense to allow the user to sort the tracks by either chromosome name or score, as is being done in the search view?

**Comment by adf-ncgr** [comment]
I think it makes sense to enable sorting within groups, but you wouldn't want to sort things in such a way that the groups were interleaved (I don't think this would make sense, though perhaps there is some use case for it out there). The scores are with respect to the HMM for each group, right?

**Comment by alancleary** [comment]
Yes, the scores (probability of Viterbi path) are relative to the group each track is aligned to, so the sorting would be within the groups. Not sure how hard this will be. Regardless, I'll change the label to enhancement.

**Comment by alancleary** [comment]
Implemented in commits d22a5ccf09e3b4c9a3d8a7d7297a84e9a575183a and 9d33c79f7d92794d8f1501178870f14b83e8e86d.
