### ISSUE TITLE
ordering of gene families in legend for pan-view

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/lis_context_viewer#78]
I know we've discussed this previously, but I couldn't find an issue for it so adding one. The idea is to facilitate use of the legend-view interactivity by making the order of the gene family list correspond in some helpful way to an order of families implied by the pan view. In the search view, this is done (I think) by going in "reading order" (ie scanning tracks from left-to-right and reading tracks from top to bottom) and adding new families to the legend as they are encountered. This would probably be fine for pan-view as well; an alternative that might be slightly better would be to go column by column rather than track-by-track; this would at least accentuate the fact that the top track is not privileged in the pan view. If we go this latter route, we'll need to take into account the fact that each new group is a new set of columns (ie don't start the next group until you've handled all the families in the current group). I'm thinking that we don't want to divide the legend per-group since groups will share some genes, but I could also imagine repeating families in different sections of the legend representing the different groups.

**Comment by alancleary** [comment]
Done in commit e56672f465c50dbab6430bc0e8f9bb6f91b30c9f.
