### ISSUE TITLE
explore parameter interaction behavior for query and grouping parameters in panview

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/lis_context_viewer#79]
per recent discussion, there appear to be some fairly non-intuitive behaviors that can be induced by increasing the number of neighbors on a segment that has been nicely aligned under the defaults; under certain circumstances it appears that you can lose all alignment (ie nothing gets grouped by the FR algorithm). Refer to examples in email regarding hapmap data.

**Comment by alancleary** [comment]
Turns out there was a bug that was causing this confound interplay between parameters. Should have been taken care of in commit eb7c3f3c8aac3d8373ac1a81ae1c1231845f7606, but I'll wait for your review, @adf-ncgr , before closing the issue.

**Comment by alancleary** [comment]
Moving back to In Progress. It seems all tracks are in a single group now!

**Comment by adf-ncgr** [comment]
being all in a single group isn't necessarily wrong; but it isn't necessarily right either. I trust you to use your judgment on whether the groupings seem plausible given the alignments produced/commonalities noted.

**Comment by alancleary** [comment]
Yes, in some cases one group is expected. But when I said "all tracks", I meant every track in every view!

One of the bug fixes in the previous commit was actually breaking working code. The "fix" has been undone in commit e27f4f8682bb024986e6237d6d467e3a29b5edad. Ready for review.

**Comment by adf-ncgr** [comment]
OK, I need to get "exterminator" set up somewhere- probably will update the instance on laasi.
will try to have you some reviews by tomorrow AM (hopefully rave reviews!)

**Comment by alancleary** [comment]
At this point I think the parameter interaction is as good as it's going to get. If we're still not satisfied, then it might be worth considering a different clustering algorithm. Closing.
