### ISSUE TITLE
Can species tracks be ordered by user?

### ISSUE THREAD

**Issue by ekcannon** [legumeinfo/lis_context_viewer#81]
For example, I wanted to compare the order of gene families for a soybean gene model, to that of a common bean gene model, but the latter was too far down to see both at the same time. Alternatively, can tracks for species that are not of interest be turned off?

**Comment by adf-ncgr** [comment]
ordering can currently only be done either alphabetically or by "edit distance" (accessed via the up-down arrow icon for "resort"); but you can use filtering (funnel icon) to subset the display of tracks. the query track will always be displayed, but the aligned tracks are subjected to filtering (regex-based); if you want to only display common bean, put phavu in the filter box, or phavu|glyma if you want to retain the homeologous regions. do you think explicit user-determined order is useful enough to warrant additional UI complexity given what's available for achieving what you were after?

**Comment by alancleary** [comment]
This issue is stale and the given solution still works. Closing.
