### ISSUE TITLE
decide on user-friendly default parameters for clustering

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/lis_context_viewer#86]
in my exploration so far, the 0.5 identity setting seems arguably too lenient (often the alignments produced seem to be fighting hard to establish their own subclusters); 0.9 seems to produce more pleasing consistency of grouping with alignment, though it may have a tendency to kick out tracks into the unclustered pile (perhaps with good reason). I suspect this is something for which there may be no firm basis for deciding, but given that %98 of our users will probably never fiddle the params we probably want to ensure we create a good first impression. Do you want to leave this up to my personal (and algorithmically uninformed) taste or do you have any feelings on the matter?

**Comment by alancleary** [comment]
See my first comment on #85. It might be better to go with something a little more lenient so that some tracks aren't unfavorably excluded from a grouping.

**Comment by adf-ncgr** [comment]
more lenient than 0.9? OK. some tests following my initial post of this message suggest that 0.7 or so might be a good compromise (only coincidentally being the arithmetic mean of 0.5 and 0.9).

**Comment by alancleary** [comment]
OK, the behavior of the identity parameter has drastically changed since the beginning of this thread (see #85). After playing around with the current version of the FR algorithm I've taken the liberty of setting the default value of the identity parameter to 0.85 (commit e2c1c7a119a87a2a5ad34dbd9885618b5f11b872).

**Comment by alancleary** [comment]
After playing with it some more I'm now leaning towards 0.75...

**Comment by alancleary** [comment]
There hasn't been any movement on this for a while so I'm assuming the existing defaults are adequate. Closing.
