### ISSUE TITLE
microlegend seems to not get populated if query track finds no results

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/lis_context_viewer#97]
e.g. /#/search/lis/aradu.Aradu.00ADX?neighbors=10&sources=lis&matched=4&intermediate=5&algorithm=repeat&match=10&mismatch=-1&gap=-1&score=30&threshold=25&regexp=&order=chromosome

this does not seem to be a problem with the older version (still on legumeinfo.org for the next couple of hours ), but I am seeing it with the new version.

**Comment by adf-ncgr** [comment]
note that the genes in the query track do get colors assigned, although one might argue that this behavior is incorrect if they are technically singletons (I'm not arguing it, however!)

**Comment by alancleary** [comment]
Fixed in commit 3a13e6b219e391d6f8001b5a1f22bc93ad603daa
